### PR TITLE
Plural forms, bug fixed.

### PR DESCRIPTION
**Pull request by francescarpi**

### CODE REVIEW

**Comment by jucrouzet** [comment]
It's seems ok a for a simple plural rule like english or french (single, plural).
There is some languages with more than two plural forms, example : 
- Polish : `nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);`
- Irish : `nplurals=5; plural=n==1 ? 0 : n==2 ? 1 : (n>2 && n<7) ? 2 :(n>6 && n<11) ? 3 : 4;`

AFAIK, the model is 
(nplurals:`<number of plural forms>`; plural:`<a list of formula separated by : whose length is equal to nplurals >`)

Here is a list of plural forms by language : http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

**Comment by jucrouzet** [comment]
The good news is that the formulas seems to be valid javascript, so you can wrap it in a `new Function` that will return the index to use in array : 

```js
code = "return n==1 ? 0 : n==2 ? 1 : (n>2 && n<7) ? 2 :(n>6 && n<11) ? 3 : 4;"
f = new Function("n", code);

// > a(0)
// 4
// > a(1)
// 0
// > a(1000)
// 4
// > a(8)
// 3
// > 
```

**Comment by francescarpi** [comment]
Hi!

Well, I think that I already have it. And now is compatible with all language rules ;).

What do you think about this code?

Thanks.

**Comment by jucrouzet** [comment]
Code LGTM, I will try on a real app tonight with complex datas
Thank you !

**Pull request merged**
